# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'about_membership.ui'
##
## Created by: Qt User Interface Compiler version 6.10.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from PySide6.QtCore import (QCoreApplication, QDate, QDateTime, QLocale,
    QMetaObject, QObject, QPoint, QRect,
    QSize, QTime, QUrl, Qt)
from PySide6.QtGui import (QBrush, QColor, QConicalGradient, QCursor,
    QFont, QFontDatabase, QGradient, QIcon,
    QImage, QKeySequence, QLinearGradient, QPainter,
    QPalette, QPixmap, QRadialGradient, QTransform)
from PySide6.QtWidgets import (QApplication, QFrame, QLabel, QMainWindow,
    QSizePolicy, QWidget)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        if not MainWindow.objectName():
            MainWindow.setObjectName(u"MainWindow")
        MainWindow.resize(1096, 625)
        palette = QPalette()
        brush = QBrush(QColor(255, 255, 255, 255))
        brush.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush)
        brush1 = QBrush(QColor(197, 197, 197, 255))
        brush1.setStyle(Qt.BrushStyle.SolidPattern)
        palette.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.Window, brush1)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush)
        palette.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.Window, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Base, brush1)
        palette.setBrush(QPalette.ColorGroup.Disabled, QPalette.ColorRole.Window, brush1)
        MainWindow.setPalette(palette)
        font = QFont()
        font.setHintingPreference(QFont.PreferDefaultHinting)
        MainWindow.setFont(font)
        self.centralwidget = QWidget(MainWindow)
        self.centralwidget.setObjectName(u"centralwidget")
        self.label_3 = QLabel(self.centralwidget)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(30, 370, 181, 161))
        self.label_3.setPixmap(QPixmap(u"images/bronze.png"))
        self.label_3.setScaledContents(True)
        self.label_3.setOpenExternalLinks(False)
        self.label_3.setTextInteractionFlags(Qt.TextInteractionFlag.LinksAccessibleByMouse)
        self.label_4 = QLabel(self.centralwidget)
        self.label_4.setObjectName(u"label_4")
        self.label_4.setGeometry(QRect(250, 250, 181, 161))
        self.label_4.setPixmap(QPixmap(u"images/silver.png"))
        self.label_4.setScaledContents(True)
        self.label_4.setOpenExternalLinks(False)
        self.label_4.setTextInteractionFlags(Qt.TextInteractionFlag.LinksAccessibleByMouse)
        self.label_5 = QLabel(self.centralwidget)
        self.label_5.setObjectName(u"label_5")
        self.label_5.setGeometry(QRect(560, 170, 181, 161))
        self.label_5.setPixmap(QPixmap(u"images/gold.png"))
        self.label_5.setScaledContents(True)
        self.label_5.setOpenExternalLinks(False)
        self.label_5.setTextInteractionFlags(Qt.TextInteractionFlag.LinksAccessibleByMouse)
        self.label_6 = QLabel(self.centralwidget)
        self.label_6.setObjectName(u"label_6")
        self.label_6.setGeometry(QRect(870, 80, 181, 161))
        self.label_6.setPixmap(QPixmap(u"images/Business.png"))
        self.label_6.setScaledContents(True)
        self.label_6.setOpenExternalLinks(False)
        self.label_6.setTextInteractionFlags(Qt.TextInteractionFlag.LinksAccessibleByMouse)
        self.label_2 = QLabel(self.centralwidget)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(90, 350, 61, 16))
        palette1 = QPalette()
        brush2 = QBrush(QColor(0, 0, 0, 255))
        brush2.setStyle(Qt.BrushStyle.SolidPattern)
        palette1.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush2)
        palette1.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush2)
        self.label_2.setPalette(palette1)
        font1 = QFont()
        font1.setPointSize(12)
        font1.setBold(True)
        font1.setHintingPreference(QFont.PreferDefaultHinting)
        self.label_2.setFont(font1)
        self.label_7 = QLabel(self.centralwidget)
        self.label_7.setObjectName(u"label_7")
        self.label_7.setGeometry(QRect(320, 230, 51, 16))
        palette2 = QPalette()
        palette2.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush2)
        palette2.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush2)
        self.label_7.setPalette(palette2)
        self.label_7.setFont(font1)
        self.label_8 = QLabel(self.centralwidget)
        self.label_8.setObjectName(u"label_8")
        self.label_8.setGeometry(QRect(630, 150, 41, 16))
        palette3 = QPalette()
        palette3.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush2)
        palette3.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush2)
        self.label_8.setPalette(palette3)
        self.label_8.setFont(font1)
        self.label_9 = QLabel(self.centralwidget)
        self.label_9.setObjectName(u"label_9")
        self.label_9.setGeometry(QRect(910, 60, 101, 21))
        palette4 = QPalette()
        palette4.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush2)
        palette4.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush2)
        self.label_9.setPalette(palette4)
        self.label_9.setFont(font1)
        self.label_10 = QLabel(self.centralwidget)
        self.label_10.setObjectName(u"label_10")
        self.label_10.setGeometry(QRect(20, 530, 201, 71))
        palette5 = QPalette()
        palette5.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush2)
        palette5.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush2)
        self.label_10.setPalette(palette5)
        font2 = QFont()
        font2.setPointSize(12)
        font2.setStyleStrategy(QFont.PreferDefault)
        font2.setHintingPreference(QFont.PreferNoHinting)
        self.label_10.setFont(font2)
        self.label_10.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        self.label_10.setContextMenuPolicy(Qt.ContextMenuPolicy.CustomContextMenu)
        self.label_10.setAcceptDrops(True)
        self.label_10.setFrameShape(QFrame.Shape.Panel)
        self.label_10.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_11 = QLabel(self.centralwidget)
        self.label_11.setObjectName(u"label_11")
        self.label_11.setGeometry(QRect(250, 410, 201, 71))
        palette6 = QPalette()
        palette6.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush2)
        palette6.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush2)
        self.label_11.setPalette(palette6)
        self.label_11.setFont(font2)
        self.label_11.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        self.label_11.setContextMenuPolicy(Qt.ContextMenuPolicy.CustomContextMenu)
        self.label_11.setAcceptDrops(True)
        self.label_11.setFrameShape(QFrame.Shape.Panel)
        self.label_11.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_13 = QLabel(self.centralwidget)
        self.label_13.setObjectName(u"label_13")
        self.label_13.setGeometry(QRect(830, 240, 261, 71))
        palette7 = QPalette()
        palette7.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush2)
        palette7.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush2)
        self.label_13.setPalette(palette7)
        self.label_13.setFont(font2)
        self.label_13.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        self.label_13.setContextMenuPolicy(Qt.ContextMenuPolicy.CustomContextMenu)
        self.label_13.setAcceptDrops(True)
        self.label_13.setFrameShape(QFrame.Shape.Panel)
        self.label_13.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label_12 = QLabel(self.centralwidget)
        self.label_12.setObjectName(u"label_12")
        self.label_12.setGeometry(QRect(480, 340, 376, 78))
        palette8 = QPalette()
        palette8.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush2)
        palette8.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush2)
        self.label_12.setPalette(palette8)
        self.label_12.setFont(font2)
        self.label_12.setFocusPolicy(Qt.FocusPolicy.WheelFocus)
        self.label_12.setContextMenuPolicy(Qt.ContextMenuPolicy.CustomContextMenu)
        self.label_12.setAcceptDrops(True)
        self.label_12.setFrameShape(QFrame.Shape.Panel)
        self.label_12.setAlignment(Qt.AlignmentFlag.AlignCenter)
        self.label = QLabel(self.centralwidget)
        self.label.setObjectName(u"label")
        self.label.setGeometry(QRect(150, 0, 799, 78))
        palette9 = QPalette()
        palette9.setBrush(QPalette.ColorGroup.Active, QPalette.ColorRole.WindowText, brush2)
        palette9.setBrush(QPalette.ColorGroup.Inactive, QPalette.ColorRole.WindowText, brush2)
        self.label.setPalette(palette9)
        font3 = QFont()
        font3.setPointSize(18)
        font3.setBold(True)
        font3.setHintingPreference(QFont.PreferDefaultHinting)
        self.label.setFont(font3)
        self.label.setAlignment(Qt.AlignmentFlag.AlignCenter)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)

        QMetaObject.connectSlotsByName(MainWindow)
    # setupUi

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QCoreApplication.translate("MainWindow", u"MainWindow", None))
        self.label_3.setText("")
        self.label_4.setText("")
        self.label_5.setText("")
        self.label_6.setText("")
        self.label_2.setText(QCoreApplication.translate("MainWindow", u"Bronze", None))
        self.label_7.setText(QCoreApplication.translate("MainWindow", u"Silver", None))
        self.label_8.setText(QCoreApplication.translate("MainWindow", u"Gold", None))
        self.label_9.setText(QCoreApplication.translate("MainWindow", u"Biznes paket", None))
        self.label_10.setText(QCoreApplication.translate("MainWindow", u"+1 ball va 0% chegirma", None))
        self.label_11.setText(QCoreApplication.translate("MainWindow", u"+4 ball va 5% chegirma", None))
        self.label_13.setText(QCoreApplication.translate("MainWindow", u"+Ulgurji xaridlar va maxsus narxlar", None))
        self.label_12.setText(QCoreApplication.translate("MainWindow", u"+6 ball va 10% chegirma yetkazib berish bepul", None))
        self.label.setText(QCoreApplication.translate("MainWindow", u"A'zolik xaqida", None))
    # retranslateUi

